version: "3.8"

services:
  #Postgres
  postgres-account:
    image: "postgres:15.0"
    container_name: "postgres-account"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: account_user
      POSTGRES_PASSWORD: account_pass
    volumes:
      - account-data:/var/lib/postgresql/data
    networks:
      - payment-hub

  postgres-transaction:
    image: "postgres:15.0"
    container_name: "postgres-transaction"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: transaction_db
      POSTGRES_USER: transaction_user
      POSTGRES_PASSWORD: transaction_pass
    volumes:
      - transaction-data:/var/lib/postgresql/data
    networks:
      - payment-hub

  postgres-analytics:
    image: "timescale/timescaledb:latest-pg15"
    container_name: "postgres-analytics"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: analytics_db
      POSTGRES_USER: analytics_user
      POSTGRES_PASSWORD: analytics_pass
    volumes:
      - analytics-data:/var/lib/postgresql/data
    networks:
      - payment-hub

  postgres-orchestrator:
    image: "postgres:15"
    container_name: "postgres-orchestrator"
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: orchestrator_db
      POSTGRES_USER: orchestrator_user
      POSTGRES_PASSWORD: orchestrator_pass
    volumes:
      - orchestrator-data:/var/lib/postgresql/data
    networks:
      - payment-hub

  #Kafka
  kafka-1:
    container_name: server-1
    image: apache/kafka:3.9.2
    ports:
      - "9092:9092"
    environment:
      KAFKA_CLUSTER_ID: payment-hub
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@server-1:9091,2@server-2:9091,3@server-3:9091
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9090,CONTROLLER://0.0.0.0:9091,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://server-1:9090,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
    volumes:
      - ./data/kafka1:/var/lib/kafka/data
    networks:
      - payment-hub

  kafka-2:
    container_name: server-2
    image: apache/kafka:3.9.2
    ports:
      - "9094:9094"
    environment:
      KAFKA_CLUSTER_ID: payment-hub
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@server-1:9091,2@server-2:9091,3@server-3:9091
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9090,CONTROLLER://0.0.0.0:9091,EXTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://server-2:9090,EXTERNAL://localhost:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
    volumes:
      - ./data/kafka2:/var/lib/kafka/data
    networks:
      - payment-hub

  kafka-3:
    container_name: server-3
    image: apache/kafka:3.9.2
    ports:
      - "9096:9096"
    environment:
      KAFKA_CLUSTER_ID: payment-hub
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@server-1:9091,2@server-2:9091,3@server-3:9091
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9090,CONTROLLER://0.0.0.0:9091,EXTERNAL://0.0.0.0:9096
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://server-3:9090,EXTERNAL://localhost:9096
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
    volumes:
      - ./data/kafka3:/var/lib/kafka/data
    networks:
      - payment-hub

  #services
  transaction-service:
    container_name: transaction-service
    image: compotapp/hub-transaction-service:1.0.0-SNAPSHOT
    ports:
      - "8082:8082"
    environment:
      - DB_URL=jdbc:postgresql://postgres-transaction:5432/transaction_db
      - KAFKA_BOOTSTRAP_SERVERS=server-1:9090,server-2:9090
      - grpc.client.account-service.address=static://account-service:9090
      - grpc.client.account-service.negotiation-type=plaintext
    depends_on:
      - postgres-transaction
      - kafka-1
      - kafka-2
      - kafka-3
      - notification-service
    networks:
      - payment-hub

  account-service:
    container_name: account-service
    image: compotapp/hub-account-service:1.0.0-SNAPSHOT
    ports:
      - "9090:9090"
    environment:
      - DB_URL=jdbc:postgresql://postgres-account:5432/account_db
    depends_on:
      - postgres-account
    networks:
      - payment-hub

  notification-service:
    container_name: notification-service
    image: compotapp/hub-notification-service:1.0.0-SNAPSHOT
    ports:
      - "9093:9093"
    networks:
      - payment-hub

  analytics-service:
    container_name: analytics-service
    image: compotapp/hub-analytics-service:1.0.0-SNAPSHOT
    expose:
      - "9090"
    environment:
      - DB_URL=jdbc:postgresql://postgres-analytics:5432/analytics_db
      - KAFKA_BOOTSTRAP_SERVERS=server-1:9090,server-2:9090
    depends_on:
      - postgres-analytics
      - kafka-1
      - kafka-2
      - kafka-3
    networks:
      - payment-hub

volumes:
  account-data:
    driver: local
  transaction-data:
    driver: local
  analytics-data:
    driver: local
  orchestrator-data:
    driver: local

networks:
  payment-hub:
    driver: bridge

# docker-compose -f docker/payment-hub/docker-compose.yaml up -d

# добавить health check