server:
  port: 8084

spring:
  application:
    name: saga-orchestrator

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5435/orchestrator_db}
    username: orchestrator_user
    password: orchestrator_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092,localhost:9094}

grpc:
  server:
    port: 9091