spring:
  application:
    name: analytics-service
  datasource:
    url: jdbc:postgresql://localhost:5434/analytics_db
    username: analytics_user
    password: analytics_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false