spring:
  application:
    name: account-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/account_db}
    username: account_user
    password: account_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

grpc:
  server:
    port: 9090